= Типы

== Generics
=== Общее описание
в Java менее развита и с legacy
Применяется к классам и статическим функциям/методам
Простейшая форма - именованный тип-параметр

=== ОТЛИЧИЕ ОТ JAVA
* Все применения generic-типа требуют указания типа
* Нет legacy-варианта "generic без типовых параметров"
intHolder2/stringHolder2 - это просто type
inference

=== Разрешение типов 
* Конкретные расширения имеют приоритет над обобщенными
* Если возникает неоднозначность - ошибка компиляции
* Если дважды встречается один тип-параметр - подразумеваются значения одного типа
* Если в реальности разные - ищется общий

== Nothing
* приводим к любому типу
* Результат функции, которая не завершится штатно, можно присвоить обычной типизированной переменной
* Или объявить функцию как что-то возвращающую - и при этом бросить исключение

== Out  
Ковариантность -- запись в широком смысле слова: Holder<A> подтип Holder<B>, если A подтип B

Код на джава 
```java 
void foo(Holder<String> x){
    //упадет во время компиляции
    Holder<Object> a = x;
    //не упадет
    Holder<? extends Object> b = x;
}
```

* Можем отношение наследования перенести из типа-параметра в объемлющий тип
* Если поля этого типа-параметра неизменяемы
* А если это не так - тогда "как в Java"
* Но можно добавить гибкости

https://kotlinlang.org/docs/generics.html#type-erasure