IP v4 -- 4 byte (0..225) -- всего 4 млрд адресов, на всех не хватит

Некоторые адреса не дают право выйти в интернет

192.168.\*.*

10.\*.*.*

127.\*.*.* (look_back)

224.\*.*.*

2 ip адреса находятся в локальной сети, если их часть под маской одинакова. Маска -- количество единичек до последовательности 0.

gateway -- шлюз -- адрес, по которому можно выйти во внешний мир. Это у роутера с внутренней стороны.

Отправка сообщения: Ip получателя, Ip отправителя, данные, порт получателя и отправителя. Почему на получателя тоже нужен порт? Каждая вкладка браузера -- отдельный порт.

Порт  -- это 16 битное число (2 байта) - уникальный id сетевого соединения на ПК. Т.е. где-то на сервере есть слушатель, который просматривает этот порт.

Порт зависит от соглашения протокола. Для http -- 80. Можно их указывать явно vk.com:80.

== NAT 
На роутере работает NAT -- network address t?

Каждой парсе ip(устройства):port мапится пара ip':port'. Этот мапинг сохраняется в таблице пока не выйдет какой-нибудь timeout.

Как получать пуш уведомления? Устройство-получательн каждое n времени отправляет на сервер гугла с интересующими его приложениями. Приложения помнят, что пользователь х отправлял ему когда-то что-то и отправляют эту же информацию на сервер гугла.

== DMZ 
для NAT есть разрешенный дипапазон портов, а все остальное транслируй в коробочку.

== Автономные зоны
Весь интернет разбит на 1024 автономные зоны -- непрерывный набор адресов. На граничных автономных зонах стоят компы (border gateway server), которые связываются с устройствами в других автономных зонах.

== Адресация
 Меньше вранья богу вранья 

у устройства не 1 ip адрес, а много. Может быть у каждого сетевого интерфейса и собственная маскуа, описывающая сеть. У некоторых интерфейсов мб шлюз, но не у всех. Чтобы это разрешать используют таблицу маршрутизации.

=== lookback 
Виртуальный сетевой интерфейс для удобной передачи данных внутри ПК. Например, от одного процесса другому. Де факто сеть, которая включает в себя только 1 ПК. Это 127.\*.*.* -- 256^3 адресов. И на каждый можно выделить набор портов.

Когда отправляем пакет хотим найти строчку, к которой подходят адрес и маска. 

Подходит под 0.0.0.0 -- передаем на его интерфейс (физический способ передачи по сети). Если подходит под несколько адресов, то выбирается адрес с лучшей метрикой (в виндовс с большей). Выход во внешний мир всегда имеет худшую метрику, чем локальные.

== Маршрутизация 
Если напрямую шлем коту, то пишем макадрес кота. Если через шлюз, то пишем макадрес шлюза. Шлюз, когда получил, сравнивает: видит что мак его, а ип нет. Меняет парты  и отправляет дальше.

Откуда брать маки? ARP - address resolution protocol. Отправляет широковещательный пакет с вложенным ip адресом. Его получат все устройства в локальной сети, но ответит только тот, который имеет этот ip.

Если каждый раз отправлять APR запрос, то мы умрем. Поэтому в ПК хранится табличка. 

Зачем вообще мак адрес? Потому что данные передаются физически. Теоретически можно использовать и IP, но реализовали так.

== ARP спуфинг 
Реагирую на все ARP запросы, которые идут и говорю, что это я. Притворяюсь шлюзом.

След лекция: разные механизмы сетевых атак.